package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/julien-sobczak/the-notewriter/internal/core"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(installGitHooksCmd)
}

var installGitHooksCmd = &cobra.Command{
	Use:   "install-git-hooks",
	Short: "Install Git hooks to automate nt commands",
	Long:  `Install Git hooks (pre-commit, post-commit, pre-push) to automatically run nt commands.`,
	Run: func(cmd *cobra.Command, args []string) {
		// Find Git repository root
		gitRoot, err := findGitRoot()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}

		// Check for existing hooks
		hooksDir := filepath.Join(gitRoot, ".git", "hooks")
		if err := checkExistingHooks(hooksDir); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}

		// Get list of remotes from config
		config := core.CurrentConfig()
		remotes := config.ConfigFile.Remotes

		// Prompt user for hook selection
		selectedHooks, selectedRemote, err := promptForHooks(remotes)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}

		// Install selected hooks
		if err := installHooks(hooksDir, selectedHooks, selectedRemote); err != nil {
			fmt.Fprintf(os.Stderr, "Error installing hooks: %v\n", err)
			os.Exit(1)
		}

		fmt.Println("✅ Git hooks installed successfully!")
	},
}

// findGitRoot finds the Git repository root directory
func findGitRoot() (string, error) {
	cmd := exec.Command("git", "rev-parse", "--show-toplevel")
	output, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("not a git repository (or any of the parent directories)")
	}

	gitRoot := strings.TrimSpace(string(output))

	// Verify .git directory exists
	gitDir := filepath.Join(gitRoot, ".git")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		return "", fmt.Errorf(".git directory not found in %s", gitRoot)
	}

	return gitRoot, nil
}

// checkExistingHooks checks if any of the hooks already exist
func checkExistingHooks(hooksDir string) error {
	hookNames := []string{"pre-commit", "post-commit", "pre-push"}

	existingHooks := []string{}
	for _, hookName := range hookNames {
		hookPath := filepath.Join(hooksDir, hookName)
		if _, err := os.Stat(hookPath); err == nil {
			existingHooks = append(existingHooks, hookName)
		}
	}

	if len(existingHooks) > 0 {
		return fmt.Errorf("the following hooks already exist: %s\nPlease remove them manually before installing new hooks", strings.Join(existingHooks, ", "))
	}

	return nil
}

// installHooks installs the selected hooks
func installHooks(hooksDir string, selectedHooks []string, remoteName string) error {
	// Ensure hooks directory exists
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	for _, hookName := range selectedHooks {
		hookPath := filepath.Join(hooksDir, hookName)
		hookScript := generateHookScript(hookName, remoteName)

		// Write hook script
		if err := os.WriteFile(hookPath, []byte(hookScript), 0755); err != nil {
			return fmt.Errorf("failed to write %s hook: %w", hookName, err)
		}

		fmt.Printf("✅ Installed %s hook\n", hookName)
	}

	return nil
}

// generateHookScript generates the bash script for a given hook
func generateHookScript(hookName, remoteName string) string {
	switch hookName {
	case "pre-commit":
		return `#!/bin/bash
# Auto-generated by nt install-git-hooks

set -e

echo "Running nt lint..."
nt lint

echo "Running nt add..."
nt add .

exit 0
`
	case "post-commit":
		return `#!/bin/bash
# Auto-generated by nt install-git-hooks

set -e

echo "Running nt commit..."
nt commit

exit 0
`
	case "pre-push":
		return fmt.Sprintf(`#!/bin/bash
# Auto-generated by nt install-git-hooks

set -e

echo "Running nt push..."
nt push %s

exit 0
`, remoteName)
	default:
		return ""
	}
}
